### ISSUE TITLE
Nested forms and helpers with ERB

### ISSUE THREAD

**Issue by joaodiogocosta** [padrino/padrino-framework#1785]
Guys, I'm trying to implement a nested form where I can add multiple instances of the child object using a `Add Whatever` button in the interface.

In Rails, one (old) method to do this is to create a helper that generates nested fields everytime you click that `Add Whatever` button:

```
def link_to_add_fields( text, f, association, target )

  new_object    = f.object.class.reflect_on_association(association).klass.new
  template_path = "#{association}/fields" 

  template = f.fields_for(association, new_object) do |builder|
    render(template_path, :f => builder)
  end

  link_to text, "#", onclick: "add_#{association}_fields(this, \"#{escape_javascript(template)}\", \"#{target}\")"

end
```

However, when I try to do this in Padrino the `f.fields_for (...)` block doesn't render to the template variable, but instead is displayed in the layout.

This (http://stackoverflow.com/a/26174803/391229) stack overflow answer might describe the reason why.

Thanks

**Comment by arunagw** [comment]
Haunted by this bug today. Anyone got any good solution for this?

**Comment by ujifgc** [comment]
No. A passable solution is here: 7d198d85c78a004b2299b71a0dd08da11c3a3368 at lines 97 and 101

**Comment by sshaw** [comment]
I have a gem, [padrino_bootstrap_forms](https://github.com/sshaw/padrino_bootstrap_forms), that had to do [some hacky stuff](https://github.com/sshaw/padrino_bootstrap_forms/blob/v0.1.0/lib/bootstrap_forms/helpers/form_tag_helper.rb#L71-L81) to get Padrino to work with HAML, Slim, and ERB with the type of stuff outlined by @joaodiogocosta. And, as you can see [here](https://travis-ci.org/sshaw/padrino_bootstrap_forms/jobs/9306231), it worked. Note [the Padrino version](https://travis-ci.org/sshaw/padrino_bootstrap_forms/jobs/9306231#L46): 0.11.2  

Now, I'm currently upgrading the gem and noticed that view block helper related tests are failing. The difference is the Padrino version:

```
~/code/ruby/padrino_bootstrap_forms >bl padrino
/Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-0.11.4
~/code/ruby/padrino_bootstrap_forms >rspec -fd --fail-fast -e'BootstrapForms using haml bootstrap_actions renders using'
Run options: include {:full_description=>/BootstrapForms\ using\ haml\ bootstrap_actions\ renders\ using/}

BootstrapForms
  using haml
    bootstrap_actions
      renders using content from the provided block

Finished in 0.07261 seconds
1 example, 0 failures
```

```
~/code/ruby/padrino_bootstrap_forms >bl padrino
/Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-0.12.4
~/code/ruby/padrino_bootstrap_forms >rspec -fd --fail-fast -e'BootstrapForms using haml bootstrap_actions renders using'
Run options: include {:full_description=>/BootstrapForms\ using\ haml\ bootstrap_actions\ renders\ using/}

BootstrapForms
  using haml
    bootstrap_actions
      renders using content from the provided block (FAILED - 1)

Failures:

  1) BootstrapForms using haml bootstrap_actions renders using content from the provided block
     Failure/Error: req(format, "bootstrap_actions_with_block").should equal_xml %|<div class="form-actions"><a class="btn cancel" href="javascript:history.go(-1)">No!</a></div>|
     NoMethodError:
       undefined method `match?' for nil:NilClass
     # ./spec/support/form_tag_helpers.rb:55:in `block (3 levels) in <top (required)>'

Finished in 0.06657 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/support/form_tag_helpers.rb:54 # BootstrapForms using haml bootstrap_actions renders using content from the provided block
```

So something between 0.11.4 and 0.12.4 made things worse. I hope this helps.

**Comment by sshaw** [comment]
And note the the above does not work with 0.13.1. It's attempting to render:

```haml
- bootstrap_actions do
  = bootstrap_cancel_tag "No!"
```

**Comment by ujifgc** [comment]
The correct HAML syntax would be:

```haml
= bootstrap_actions do
  = bootstrap_cancel_tag "No!"
```

**Comment by sshaw** [comment]
> The correct HAML syntax would be: ...

Hummm yes that is a somewhat recent change, but regardless, the test are failing in Slim and ERB. 

I think I've tracked at least the ERB failure to [this](https://github.com/sshaw/padrino-framework/blob/0.12.0.rc1/padrino-helpers/lib/padrino-helpers/output_helpers/erb_handler.rb#L20). Here,  given code like: 

```erb
<%- bootstrap_actions do %>
  <%= bootstrap_cancel_tag "No!" %>
<% end %>

```
`block.binding.eval('defined? __in_erb_template')` is always `false`. 

And of course in this case `<%= bootstrap_actions do %> ...` would be a syntax error 😈

**Comment by ujifgc** [comment]
By the way, your tests pass on 0.12 branch if you add

```
  s.add_development_dependency "erubis"
```

to your `.gemspec`.

**Comment by ujifgc** [comment]
Added some fixes to Padrino master and 0.12 branches.

Here is a PR that would make your library compatible with 0.13 and 0.12: https://github.com/sshaw/padrino_bootstrap_forms/pull/11

**Comment by ujifgc** [comment]
To be clear, these fixes do not relate to the OP issue which only appear when you call render an erb, from which you call another helper from which you call render another erb again.

**Comment by sshaw** [comment]
> Here is a PR that would make your library compatible with 0.13 and 0.12: sshaw/padrino_bootstrap_forms#11

Thanks for this. 

> By the way, your tests pass on 0.12 branch if you add `s.add_development_dependency "erubis"`

If `erubis` is required to use ERB in Padrino then this should be required by `padrino-helpers`.

**Comment by ujifgc** [comment]
There is no way to predict if the user would use Haml, Slim of ERB for her templates, hence neither of those are required by padrino-helpers. If you generate a project from scratch, padrino-gen properly adds Erubis requirement to the project Gemfile if the user specifies ERB as her template engine.

**Comment by ujifgc** [comment]
@sshaw looks like your tests also pass on Padrino master without erubis.

**Comment by ujifgc** [comment]
Oh, I remember now. Stdlib ERB support was implemented by #1783 and released with Padrino 0.13. Before that Erubis was required.

**Comment by ujifgc** [comment]
I backported eec1d4ac47fe833b21b327b44a128dc0fa23a35b, db6d3f8a7f817a85452f8fd100c45d142decd386, fac77b160840f6eb33fea76584830a28066f1576, ab1b01905c471e780ddbb4f3f5e0f9177df60209 to 0.12 branch. Stdlib ERB should work on #2031 release without requiring Erubis.
