### ISSUE TITLE
[BUG] 1.15.2 Running "bundle exec rake ar:reset" throws an exception undefined local variable or method `less_than_active_record_6_1' for main:Object

### ISSUE THREAD

**Issue by DimitriosLisenko** [padrino/padrino-framework#2268]
#### Do you want to request a *feature* or report a *bug*?
It's a bug

#### What is the current behavior?
Running "bundle exec rake ar:reset" throws an exception.

```
$ bundle exec rake ar:reset
rake aborted!
NameError: undefined local variable or method `less_than_active_record_6_1' for main:Object
Did you mean?  less_than_active_record_6_1?
               less_than_active_record_6_0?
               less_than_active_record_5_2?
.../gems/padrino-gen-0.15.2/lib/padrino-gen/padrino-tasks/activerecord.rb:455:in `configuration_hash'
```

*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*

#### What is the expected behavior?
The expected behaviour is that there is no exception thrown.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?
Padrino 1.15.2. Works on Padrino 1.15.1.

**Comment by DimitriosLisenko** [comment]
Have a PR that resolves the issue here: https://github.com/padrino/padrino-framework/pull/2267

**Comment by nesquena** [comment]
Thanks and merged for next release

**Comment by kevin-j-m** [comment]
Thanks for the report, fix, and merge. Is there a release planned to include this? Sorry, I'm not familiar with Padrino's release cadence/process.

Thanks again for all the work!

**Comment by nesquena** [comment]
> Thanks for the report, fix, and merge. Is there a release planned to include this? Sorry, I'm not familiar with Padrino's release cadence/process.
> 
> 
> 
> Thanks again for all the work!

I'm waiting to see if any other bug reports and fixes come in after our latest release. I'll do another release within 30 days.

**Comment by kevin-j-m** [comment]
Hi @nesquena, I hope all is well. Are there plans to release this soon? 

I know we can point to the GitHub repo in the meantime, but it'd be a big help to get this out on rubygems as well. Thanks!

**Comment by nesquena** [comment]
@kevin-j-m @jkowens Pushed live 0.15.3 with all the latest fixes

**Comment by kevin-j-m** [comment]
Thank you!
