### ISSUE TITLE
Could not send email as a not existed method in ext.rb

### ISSUE THREAD

**Issue by grasp** [padrino/padrino-framework#2021]
I can sent email only after comments the line in padrino-mailer  ext.rb 118 line.
`
      encoded.to_lf.split("\n").each { |line| logger << ("  " + line) } if logger.debug?
`

`def do_delivery_with_logging
      logger.debug "Sending email to: #{destinations.join(" ")}"
      encoded.to_lf.split("\n").each { |line| logger << ("  " + line) } if logger.debug?
      do_delivery_without_logging
    end
    alias_method_chain :do_delivery, :logging if Padrino.respond_to?(:logger)
`
other wise , a exception will pop up

NoMethodError - undefined method `to_lf' for #<String:0x007fad3e6a10b0>:
	/Users/hunter/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/padrino-mailer-0.13.1/lib/padrino-mailer/ext.rb:118:in `do_delivery_with_logging'
	/Users/hunter/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mail-2.6.4/lib/mail/message.rb:239:in `deliver'
	/Users/hunter/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/padrino-mailer-0.13.1/lib/padrino-mailer/helpers.rb:113:in `deliver'
	/Users/hunter/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/padrino-mailer-0.13.1/lib/padrino-mailer/helpers.rb:49:in `deliver'

**Comment by ujifgc** [comment]
Fixed on master by 1072424206277ff05e947d238edb5dddee430933.

To fix on 0.13.1 add `gem 'mail', '2.6.3'` to your app Gemfile.

Broken by https://github.com/mikel/mail/commit/9b0620d67c997ab80cf67cc7ecfde3a78fd87377
