### ISSUE TITLE
haml 6/7 block helpers raise NoMethodError in 0.16.1 (fix on master but not released)

### ISSUE THREAD

**Issue by kenchan** [padrino/padrino-framework#2322]
#### Do you want to request a *feature* or report a *bug*?

Neither exactly — a release request, in the same spirit as #2315. The bug is already fixed on master (#2317); it just hasn't shipped yet.

#### What is the current behavior?

With the latest released `padrino-helpers` (0.16.1) and haml 6 or 7, any block-style helper used inside a haml template raises:

```
undefined method 'block_is_haml?' for #<...> (NoMethodError)
padrino-helpers-0.16.1/lib/padrino-helpers/output_helpers/haml_handler.rb:14:in 'engine_matches?'
```

This currently breaks [Middleman](https://github.com/middleman/middleman) for anyone on released gems: `link_to ... do`, `content_for`, and nested layouts all raise inside haml templates. Middleman depends on `padrino-helpers >= 0.15, < 0.17`, so a plain `bundle install` resolves 0.16.1 and hits this.

In 0.16.1, `haml_handler.rb` chooses between `HamlHandler` and `HamlitHandler` based on whether Tilt resolves `.haml` to `Padrino::Rendering::HamlTemplate`. Since 0.16, `padrino/rendering.rb` registers that template whenever the haml gem is present, so the legacy `HamlHandler` is always selected — and its `engine_matches?` calls `Haml::Helpers#block_is_haml?`, which haml >= 6 removed.

That is exactly what #2317 fixed by switching the branch to a `Haml::VERSION >= 6` check. 0.16.1 was tagged on 2026-03-27, one day before #2317 merged (2026-03-28), so the released gem still has the old logic.

#### What is the expected behavior?

Block-style helpers work in haml templates, as they already do on master.

I can confirm master fixes it — #2303 suggests that's the useful thing to report. Against a clean Middleman checkout with today's dependency resolution (haml 7.5.0, tilt 2.9.0, Ruby 4.0.6):

```ruby
# Gemfile
gem 'padrino-helpers', github: 'padrino/padrino-framework', glob: 'padrino-helpers/*.gemspec'
```

```console
# padrino-helpers 0.16.1 (released)
$ bundle exec cucumber features/helpers_link_to.feature:32 …
# => undefined method 'block_is_haml?' … (3 scenarios failed)

# padrino-helpers master (167044f)
$ bundle exec cucumber features/helpers_link_to.feature:32 …
# => 3 scenarios (3 passed)
```

No changes were needed on the Middleman side — master alone fixes it.

#### Request

Would you consider cutting 0.16.2 from master? That would unblock Middleman without either project needing a workaround. (There are four other unreleased commits since 0.16.1, including #2319, but #2317 is the one blocking us.)

Happy to test a prerelease against Middleman's suite if that would help.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

- padrino-helpers 0.16.1 (broken) / master 167044f (works)
- haml 7.5.0 and 7.4.1 (both affected); tilt 2.9.0
- Ruby 4.0.6, Linux

Yes — it worked with padrino-helpers 0.15.x, where `Tilt.template_for('.haml')` did not resolve to Padrino's own template, so the harmless `HamlitHandler` was selected instead.
