### ISSUE TITLE
Padrino does not work in Ruby 1.9.2

### ISSUE THREAD

**Issue by mvidaurre** [padrino/padrino-framework#244]
=> Problem loading config/boot.rb
=> undefined method `bundle' for Padrino:Module

I'm using rvm and in Ruby 1.8.7-p249 Padrino is working fine
